### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by masuzawa1** [masuzawa1/chat-space#24]
# IPアドレス
52.197.28.14

**Comment by kohei-isoda** [comment]
増澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ 自動更新で最新のメッセージを所得した際に、投稿日時がundefinedになっている**
[![Screenshot from Gyazo](https://gyazo.com/7f27b330f37f4baf9cbd26ffa59394e6/raw)](https://gyazo.com/7f27b330f37f4baf9cbd26ffa59394e6)

**◯ ログアウトをしようとすると以下のエラーが出てしまう**
[![Screenshot from Gyazo](https://gyazo.com/e1de1d5aa807dfdde0dc4465925b5f13/raw)](https://gyazo.com/e1de1d5aa807dfdde0dc4465925b5f13)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kohei-isoda** [comment]
修正お疲れ様でした！
問題ございませんでしたので、LGTMとさせて頂きます🎉 おめでとうございます！

**Comment by masuzawa1** [comment]
ありがとうございました！！
